name: Daily Compliance Audit

on:
  workflow_dispatch: {}  # Allow manual triggers
  schedule:
    - cron: "0 8 * * *"  # 08:00 UTC daily

# Set permissions for OIDC
permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for actions/checkout

jobs:
  audit:
    name: Run compliance scripts & tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: GitHubActions-ComplianceAudit

      - name: Run unit tests
        run: pytest -q

      - name: Execute compliance scripts
        run: |
          python scripts/fafo_checker.py || true
          python scripts/guardduty_findings_summary.py || true
          python scripts/config_noncompliant_rules.py || true
          python scripts/unused_iam_access_keys.py || true
          python scripts/list_s3_buckets.py || true

      - name: Upload Excel evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compliance-evidence
          path: |
            *.xlsx
            guardduty_findings_summary.xlsx
            config_noncompliant_rules.xlsx
            iam_unused_access_keys.xlsx
            iam_users_without_mfa.xlsx
