# Update the workflow file
cat > .github/workflows/compliance_audit.yml << 'EOF'
name: Daily Compliance Audit

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 08:00 UTC daily
  workflow_dispatch:  # Allow manual triggers

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write  # For AWS OIDC auth (recommended over long-lived keys)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # AWS Authentication (using OIDC - recommended)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # If using IAM roles
        aws-region: us-east-1

    # Run all compliance checks
    - name: Run IAM MFA Check
      run: python scripts/fafo_checker.py

    - name: Run S3 Bucket Check
      run: python scripts/list_s3_buckets.py

    - name: Run GuardDuty Findings Check
      run: python scripts/guardduty_findings_summary.py

    - name: Run Config Rules Check
      run: python scripts/config_noncompliant_rules.py

    - name: Run Unused IAM Keys Check
      run: python scripts/unused_iam_access_keys.py

    - name: Run EC2 Compliance Check
      run: python scripts/ec2_compliance_check.py

    # Upload all reports as artifacts
    - name: Upload Compliance Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: compliance-reports
        path: |
          *report.xlsx
          *audit.log
        retention-days: 7

    # Optional: Send Slack notification on failure
    - name: Notify on Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_TITLE: "Compliance Check Failed"
        SLACK_MESSAGE: "One or more compliance checks failed. Check the workflow run for details."
        SLACK_COLOR: "danger"
